language: java
jdk: openjdk8
env:
  global:
    #SONATYPE_USERNAME
    - secure: akAh+eCG+jK8FIDB/boVtgyFtYeNpLoz4PL+4PWYDTlKVt4iquMyky32m5mvSVTZc1NdlS2YHg4FHEyLz5nKUYh+WtBjP6C5PWgpJa752EzLc1NsQq2sqr6Ghxkg09Gzeda4lOkZaU/tbATwwXKGpirjYZVvsjIaJ8sEL7ptao+TdWIkZUuuGcJJ7zqm7168d0pqGmwXaYywoZ6yVq/7XK4a7MpELyipSQTt1a8BIgWBZ+d4NipB/99DjD1Hr0IEbrlvk6d2nYqhIty2bRxx/pdxrgC/mw3LP5k08FpY5IlX7H5JykpLsSjmL8GGao9/ywEvwKYMJRpTk2WuLKwaRtlfWSQ4Y15b1Tb2ydcR/wnrzfW9kV1quspEjf/sB4TrxPlYOwF/9OVs3xYPRFFFFUEOEFm1ILJFZpzLrrEFles8FaoirbOj43Bpug8Rh6ZJ2Bmb0weQZ028yGk8ye/0qbPX6C2XbHYgDyT5Jj6fQ0vzEHnsvGw5NOPZ2AoA42TFivQr7U+Al4NCMXpzF8cG9uMe6KlPw3sC1RZLNJcKG6Djj46v2wvJScH9fqF5PUIFbKsX8Z+ssTnLzJnAtHFWKCMgi+J7OtbgJHhMAEYf+Cohqi+n6dLdWDmCZUOumzXBBtp/GOVa/akgeM04/navk/kSRv9djPRRoU7YDhiBbSE=
    #SONATYPE_PASSWORD
    - secure: YYHA3coDwAeycaXVE26ih+Au0GbxRdjzxDKex0y77mKnLclHWLBysVygj1S/7zVUCLqdvPBhgG4kFhVkHvSTHcDREIPqGg4wcCHdhA/RXO+ZtdGsnUxh9mZVbekbiS/nIw4YvzKkfK2hf78upnybqx9hrB/o/3UyOsyaQxOREZsmFwXbdUUKgXHbgbvurCTNjuIjiQf9K88AcWHSEBbvjKsqD9qkh+toY7k6tnGGTUVVmM07ZB00BcHlabVIijg/6wTLj17e1EtKtT2CJ4Wci/vQ6WL2NThkoLGzzX+RWh1yEQq4kbdeQO+LMf/afosSsKb4lhxLuu/USwRgCoD13ryjs1GT9V41LcXynZ0d6yHTZW6XQ5TTa6ar1YBpUaqNew62jhm0NV3lH8/H6lod84duefibt2lOfQSDavc1wleV3tCQnEOnxyvX9nrx1Vxb/IXYSi+pHLLc0+SXbYhX6UWf1WRuiiJbil/M7oRUXNqHVoLHC516oSK6dU8vff9/uzV0Qx6ExC8JAc2jIQEwO7UMwr1GIWU5LdmPHUM2eYXkib7YlHeLcnyUGSjDbYToeOEcdbqzGYYgoWDuaIK9brWQ1LTXPzZ3gmS0i8E4ms7kjdD4vRzn5Otyc3Ktq6znpEs1bNZhvBJwPQ4DITPgi9hz6m6w6nFX07uH+6sTaIo=
    #DOCKER_PRIVATE_REPO_USERNAME
    - secure: "OPKOlbam8sgY8jrNQ7STNO7lo/e47STwAVDH7Ggsfdwy6enoYdQerOGwQ8PZdjhpgWuGhFv0LIYu+r1nKs902I63B3RnR9P4aDzFQtrBGz4vT+Vzc5swHVcOjwgF3ev183o/YVh1LxeoKVH125nj7s1pM4Bh/nJr5PrEB6VsBE+DPAruSDHPsZSMJ2VpsK2wagcoNEetgDtr+FPVT2L9LFt184hpxJ39Tg3GorFILSLZlD2SXURsRUmUn7KfRF9e/4lU7eKUCvS2twiLxm/6efyoZzCXRCFDPy7ghAu/ApYMjYtpHBGGoRTOkyuKYxIU2pRR++QkACC3iEcC1KpoiwjHOU48hWatqYsSZsLoJn7YxlsfRJ2xJu8j6k6EjnP+J3r82wbohzJkEvxQ8C7DMJda5DrRv8oQTBcEdXjh4ipGZ9e11cBisR+1OyPfvrIwpfnjeelsEy5ugDuXJKmcqYqWzz0W2Ha7YEV6pmKYQN4PSpOVfHsTkdS2nA0HG8kYXJ3LHn8w1wZqMdNrUODj3jHPQqatyxLWNjPe/1okahH72SZdYoAH8sIopU9aBC4YfixwLp9V7uytZEot2v1/9w74IF4vrFEBNELua9JGKzhdGLfnKO16rLDtD4O1/0pPVN394imRMxZTJBbz8GzKPsL4802h1/6JB3ZhSgQ6Qes="
    #DOCKER_PRIVATE_REPO_PASSWORD
    - secure: "cU8h/PsYhdafedRXQR0yL1/s3Is3yigWoUUIghXFma7ZNsFDRXnNMv95w6Rhmq2tadTmoCixo55wA9Ml2r/6s8GsXhdSuO9tSF07B4w76uZKR3LyFc52n26RqgVqbpSPFOOT9pyQjFqJQWYbK14s27sv/UJLz+WJHJfE/pemUHcuQNobDVTJxkS7kRtANR3cOv5wFToNn1+R1Wa/wosDs2rknUrkUqtiV9aN1h7d+/prmS9Ch5NWwcFSirCbYcmvTZCe+JuFvmoE2Iz+hQ6mlE5OnqBg9JvcrWpmIMqzv4MAuiHAuAd6kqcXtkjhGhlnLztwUap4Q0fwrJLc73eP5k0FR3yRSRIjENhW/wsDbFRaTkAWo3b4CjTqADg6qLpH2k9fD9a96L3gPSLPcSr6FDTVGz35l2dxvfDdGvA+FauIlvRCWr3jZPGFaM4I9lNuyT6ABGa+Ol7bGmtreVnBHL4EWyNMIxZygsgE3LdfO5FMDNGWZ8bMsp7nxU5j9BPjfiYFwhBlVvrMuLE/o/s/TjW0pyBaxL2bf2JtV0n5Mp/u2Nub4fmMUwep9UuRrMxjXj45uC1qu2UhYhwyQfhk6ZT3xJCf4RooGpc0uNI3LGivK0lrYafL9zMuq3sc3ceLGGMUX4u8+iXW5FzhUnGVqZ5BOCX3YXFUj8d55ZwBzSo="
 

services:
  - docker

before_install:
  - cp ./.travis/maven.settings.xml $HOME/.m2/settings.xml
  # - docker login -u $DOCKER_AUTH_USR -p $DOCKER_AUTH_PWD docker-dev.artifactory.datical.net

install:
  - true

jobs:
  include:
    - stage: "Integration Tests"
    - name: "Postgres Integration Tests"
      env: DB=postgres
      script: docker-compose -f ./.travis/databases.docker-compose.$DB.yml up -d && mvn integration-test
    - name: "MySQL Integration Tests"
      env: DB=mysql
      script: docker-compose -f ./.travis/databases.docker-compose.$DB.yml up -d && mvn integration-test
    - name: "MariaDB Integration Tests"
      env: DB=mariadb
      script: docker-compose -f ./.travis/databases.docker-compose.$DB.yml up -d && mvn integration-test
    # - name: "Oracle Integration Tests"
    #   env: DB=oracle
    #   script: docker-compose -f ./.travis/databases.docker-compose.$DB.yml up -d && mvn integration-test

cache:
  directories:
    - "~/.m2"
addons:
  sonarcloud:
    organization: "liquibase-oss"
    token:
      secure: LnotzNSdNvo46OiOwqCpuvG48auUnwdn78T6c2RXk39k9gtK/yBLrrSbnuBqShbYn4llXxHSLkvalfBa8Ck5w6BpMOoTInpsOWverK+0PyVmgJUv9wNIAV/9+CJS7QsBivLUf6STT7ABfbcoUiWSZUJnOS5zIZukySk+/lmMnRW2h5GniRw3N0MFPtu4G+IZ1jqWhlHovjq41JWHEGCs1+jKQPmajQLOu4RKtihEfBAVXBIorjJIXl9TcPQAbTltYPe4oRSLMRQ/Qj3PMpgsSMLRKmzJ/sgzmgzPSdlTDcsnLOjnnp6f/5mt7arZx/k78xJ+CVezr+QIIU4tpaWZqPC7T7mRh9nixQnXhNpg91zibMTb8XUIdJ8fpMlqPeHHUcKzYJ6074e0BM9JEqXSW9hvWtuscoN1nNJFyGocqaeuZ7/sUxa6zEVNRaUZ3kWoZbttkQ5AKAuYS/oVnWmkMGx5AhNqVCynGv78jIyxHSR3n4gla66+lWZqKVb1ySt8qpeHE9Ep8O0Z9EouykTCYDKJiPvwbYns5auAJdqUCuQadGh0wRBJccEDlC0LcPVilQiCrEpMOCNLmYmjVbwKm6ZFMnHfS/xB7TjgSA0CmbkX0lsDIWypwkm+TkHVg6Uw6fEpgNMOBd8W6b7XMGEUfqZcbYfPvJVSN0aeUKoYPN8=
after_success:
  - bash <(curl -s https://codecov.io/bash)
