version: '3.3'

services:
  postgres-12:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
    restart: always
    environment:
      POSTGRES_PASSWORD: LbRootPass1
      POSTGRES_DB: lbcat
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"