version: '3.3'

services:
  mysql:
    image: mysql:5
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LbRootPass1
      MYSQL_DATABASE: lbcat
      MYSQL_USER: lbuser
      MYSQL_PASSWORD: LiquibasePass1
    volumes:
      - "./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql"

  postgres-9:
    image: postgres:9
    ports:
      - "5432:5432"
    environment:
    restart: always
    environment:
      POSTGRES_PASSWORD: LbRootPass1
      POSTGRES_DB: lbcat
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"

  cockroachdb:
    image: cockroachdb/cockroach:v20.1.4
    command: start-single-node --logtostderr --insecure
    ports:
      - "26257:26257"
      - "8080:8080"