name: Release Published
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Liquibase Version'
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.collect-data.outputs.version }}
    steps:
      - name: Collect Data
        id: collect-data
        uses: actions/github-script@v4
        with:
          script: |
            core.setOutput("version", context.payload.inputs.version);

      - run: |
          echo "Publishing version ${{ steps.collect-data.outputs.version }}"

  deploy_maven:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1.2
        with:
          repository: "liquibase/liquibase"
          tag: "v${{ needs.setup.outputs.version }}"
          filename: "*"
          output-file-path: "assets"

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Publish to Maven Central
        run: |
          ls -l assets
