
name: Liquibase Url Prerequisites Check

# Job will run nightly at 02:10 EDT / 01:10 CDT
# Time below is UTC
on:
  schedule:
    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:
  urlcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "url-test.md"
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: team-liquibase
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: "${{ github.job }}: ${{ job.status }} @here"
          SLACK_USERNAME: "liquibot"
          SLACK_WEBHOOK: ${{ secrets.SNYK_LIQUIBASE_SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url
          SLACK_ICON_EMOJI: ':liquibase:'
          SLACK_LINK_NAMES: true
